services:
  mysql:
    image: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_USER=wordpress
     - MYSQL_DATABASE=wordpress
     - MYSQL_PASSWORD=wordpress

  wordpress:
    depends_on:
      - mysql
    image: wordpress
    ports:
      - "8080:80"
    environment:
     - WORDPRESS_DB_USER: wordpress
     - WORDPRESS_DB_PASSWORD: wordpress
     - WORDPRESS_DB_NAME: wordpress
     - WORDPRESS_DB_HOST: mysql:3306
